version: "3"

services:
  time-tracker-prod-fe:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:3000"
    environment:
      - REACT_APP_BACK_END_URL=http://localhost:4200/api
